---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ntfy-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgCmi6ieL8NIvwVz2wm+TkhRyoOfE98mYotpvRKkFsSCM9m5PYaVovHN01sQaHH4bN2RKblFr39y8uEV7VQUwXFde200oGeeHAeWIJTW5c265OMKAl/6Ndle1S/5BQCDkyXTN4nl0N/XdWV1m2bb3EjVRteqHA9XGu4gf9B8VqI2CaDRPh52Wwm4jn9fvwR6BV0q7np/0WFzTooz/BPGCAZBWA63BcyGRmefOxZ7mQOAxBMhAiMTHBmwhA6RUPiVSEt0ZihuJGfI1ga8OtfD7V1KcTWUrAAFuSufgfyeSUprf+cUK6kF6FV+p7tpyYb7vujzDMzyj65Ve/PL2YAmowHtR+Smar8k08kxDZF6P1FjcLh0iZKjbxl8zJbeZTM0748yIoFLlvjYd8DD0FHYRFsuIfc+CMNCwRN/g7s2LQoapPzcE6vm+Bzp9MiDRdgQ5cQVAFDNtBppj0Moru19zLVjG/9s6vZp98bi/UsStruWAq9/a2zUw0Da6Q8tUVYCtvUAlFvvIa4iFdinnOs0LDg6sCODorOCBIycqhxr8nMG//9H7HdcshIAiQWbK4jZxZcmpje2bqa45Tk52aBk2516yaKHm0emxXg3UbMsZBF2P86LMoG+KdwVpPU4JSmehymyjHvXTokhGCjevUuYzo1G2+Sd4B828Juc34aNnk2G3gka+6Eaupv5xbNNMm1NqsHsNAOLi9J2+fdWW6laAugUlQ==
    username: AgBLvx0tbbvqGCXSTOJp1xc0jpjWe9opba0THQQPW7tnVY/matR1NbnGmHm1POIfgnb4T+kSOArcf+AYrEU8Rw3Oim+hR1oCylRR4mRuPuAR6SiuzGhmrwdLSp7+MxEDf6KBcRC/OwJpbm3ePEf5yaF89K44B2QEqIt2NmC1/mPPp7uD0VRGMghb4UWJJyQKRlUDWGhIktJSzFOdO7liaUBqNg95Vp0sOkqluD4Jx4yggbYdYdHMNjrVcauPdajVSR5MFLusz4cBDJFvaBsdd9/iUlJ/MZsdvO+nkM4gsT8dpw5Wz6kO6Fs5pIAdz/UEvIx+bo1LCwUS33uLa+ktxUEGpr3UtomYEKTkPZHo/aK6AFoecvwkyxSgzoUt1ZUl4J+JfNcTlRIwa0Z/k7jbso+4Hmm5VWeX0/YrnQJkNBTkazTowgc7sb0XE+ZKlY2fh7mcawRKDToZrelh1rT2PS5RBuavTFMLm0OSLwk1pKVQgvoFQMaypufipLoZNFXUkUJkqqGo4dUDYSGCv50mAmODlr7gS8ciGn0nzu1OefCkbaLgzYKyDbYtWh8uGPvItkaIgoN5pu/iCY7YdqB6HJUHItTFMh0PKr9px6S4ZfBHvwbHHddiS3mV3dVvZt6Zq1po394aiMXQB2p7C8CgLU0O22EAAW3Psl7oY4QB5bExK6Pf+Jn5FQ0982/NKLUSMQni2R8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ntfy-secret
      namespace: argocd
