---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ntfy-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    header: AgAup2yVmZMA9zB7Yj4yZFDMZoYuL4C+qR4iVHgbl4dlqjNREFocnXrE2CzTMSnmmwdPv2O5v3yraB0QpGz60x5Qfy3kKDfTq1AScBgVjVqoe2VKqI8Iy1xQ86LSjA48h7B0fcOXAjMjcxWoDoW82dPhqiACpiF8pOabsde5OCbRm2L92sNLZzctXNLX5U49revVCHpvgR+GF3wTr6sLN2pn6tlQ6juRF+/dekrCA4sDiV5mpjBZHnfpGV2M0H58uxONPZ5BHV9PQXibweqSBHSccFa1Aej2W4xEDsHYEIOMXlSkm72+BV3FBfyEPEf09yjqlokGENDeTjUP2Abu3P/k7qfbaB8wWpRZXtTDkt07ma6MMb1BeIqakwQO1C2u3c7mkZH+r2HbLnqtvSltT1umaackTLM5sDpQB5b7p9JGj3O50sKoy+/mcpxRof1GwhbOEFDIss6yF2ZLrsT47IyV7w+4OjGHbHcGemXoZwrJDFlOkbxpEHYqVPzLJWmFkhgVjoGZpmbfsW7jQuZLiipW1rGpCPEFSsKOrv66fTnuj6CQWHfPHeVAYS0Vcu1l6abUaVSuAvbPzjXsckdbqHMOleGWW54DhWmD1eF2Q2a2F3EWwmqY6ZiL+c2m3INUv9pKzrtpTpa29wxMXcFKHpXVzTwkTvepH4EFgFzRPWyAOf2tLSviyS0msEYCwya32pRR9YVBhsZYn1YFr4b/SwmNZ3vOnvL6PeZRVlpYzyJI/D9R
    password: AgA++OBhmWT6HeXEGdzk1zaG10gM9UL9rxcBp6Pw/1Mr8ipomqajjw8loZ+h8dnIgojOi3uUPQLVa9mf/IHHr1NSxXtPz1YDomrncLR0vEUZv2D1ZOjh00UEksg2e8Lq7+iGbUrkYjJKBNlM5nihs752tK2EBP9Q8aAMOQxgyZni9NFq1cmruSiuBkXVrm+YNJWiqwH1kVsV5W7Me6fTfNucxxGyy+EytYDJV6BnmAGcKLoFmnXMWdP+naCJLbP3NzFRAkcDqLVyRCWunPROxaq2WZm0kBoQOFb9JXN4/hJ6YfJPzF7tSF+yTpCISrjrgdfVkEraicS1uNBPmesKoaX7mraPtCcj6KgphY1UDmmqDRX8Y+YXaqEj1MpM7Pac67rxB7tvfdJjXcDrAF8YkjTOr6hUH7joxGgKbA4mtlyJ5lWKJMBpLXfTGsICeLnS1Hbmo4Dwe1RTH+CmfzyghVdKgiUvgxNsO0AjDhbjUum7/IWAmDjYDksxSK1jfrsOG9vMWn0LAhd9iGk+hc/ZKDPEvL3x4wHUvkGi5whVCjmg2/rkqXXL8O+lcVH36+OR/e7DO2PfhBTCSxQnDycAPYL4YetDAYHeaAwl1q2kSmpgyZr5mxl0HO3CEqqOcwzBhQgWrr1SyN+bwSYqGezs7jixn/0rKbImLX3CTtPn7rUimF+3IPHuLcgIz9F9aNIYy851chySbZ+PCGJ2B0wZ80ypTQ==
    username: AgAh0l+2xfw2Jk1foHKKTnWn1a1RujBi/B2bsFAQs0w+oiMRhPBFklyih9Jq4HMnyGmQUzKaT+/1vMKKUakN5btsEYfGe/qiraSYcK/ZEOh+O9oP6PL5PpbPyTKH9h76XiorCOnTy0x1fPqdsHfkzqTjxc6AGBEUALTxaqGa1heqfPBjKRYE3ef6WO0OJb8Nr0///Escokd4FEn6xROVepcDFb6ay9VWCkjKLqi2EcAl66Aom0I7Q+PROWdrHPl4bbAhD/6cEArjwHSMgKUhN9kNEggSjuDuD7aQ6e3fA1fXLNj4i7ZSzFe2Sj91AFer4BAbUQO8S2s6wo0wyu9SYW8HCM9iAxpNOt5eOQOKj8T7RGxrCxn3Y1hA2hGEmUIBoBnCYxREts3tsrgGjO4YY4pSezuT6AE3cQ/zUbAT/3gniPuswP0/JhxCwue6XEArfUsuiO+tnXxYAMnLO1F00q0AklvX0t+GHmGCpaq6ep/WBnY5WAiy0hLFLtDcYt+7FNAUrfkKEZ/yG63NBq2YHK5n3xAzCHPtT4cZt34MJncxPcSmKjsPW4rh/4K8L8sJoDWFIY35+/TIq1kTkaoVzo71lTE+Cpn3OFYxZ4CNnOxUJCEcP7BD5Egh9IVX2aRT3wEcJ52UdzBgcjzUt8efp4IbUlBmz+EOaYiREChm9smEqk/JrdB5HIf22xrzwBY8sUQUin4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ntfy-secret
      namespace: argocd
