---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    header: AgCRNME0ujj9SJvbESYWKVLmemmj9DhsLYfRysngpIABI7qNm56NP7JfZjBIVUXI3WhDGmNPYjT39WQoEjcBRLP+7o2v0AGztEiWqtNwnqCoyjFVOSCMyToDTYjy+EqZAjVSBE12eQCJuciiF+c8W9sg7JZjRu/0kQI4xh652wXJRER5j3F6yliU3C3YwD5Kbz70hM2PlgFAZcyIInzlv0I9L8dwwICxjkn2aNS3CZpgU4TVsBkcJouS21ZFGhTk01ASXdVbi4LvIBqoQs7WH97/krAin48K11nDHfxi6d0SRbn+WY8hM8v9d/2PKxpBLp+na9IpJBCjmyMdvpddkq1HCQwJPPgo8zvhZaZVbQCvpVn/tmG6RD40wpTezNt9PvUFfY13NgwibHrJ+ukvhpjs7C8Z04np3q9QGWisxvp4DxHEESoS3FWno70H0vJ3dPiMZrAMLZDaAZKmbXgJ4rSQnD8VlLYqy0Ou+5OeB05w/M/j22temfHBgzc14XXu7Ow7a8c3Bd3RFEHfGIF+UgOraAgOM9PZmpGmNfRc3tvkGIdLmzqcFy7D3ot8bP0almYBz9wZqZYn8THw76L4jB6yYKLSZfVBYHrYAOui+T/9/SOiJcZ6F0uW01mGbemINb9IguAK1oWGHUhA60hkQrF5WoNZIJCqNegmEzhcq8Ld0ONdRW3LdHn4l2xcGczK5yIbepRfAvG6I9Uh7VxW/EYREmWFyHKZRLN8+bPs/byGae4O
  template:
    metadata:
      name: ntfy-secret
      namespace: argocd
