apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  entryPoints:
    - websec-int
  routes:
    - match: Host(`pgadmin.{{ .Values.global.domains.internal }}`)
      kind: Rule
      middlewares:
        - name: rate-limit-strong
          namespace: traefik-system
        - name: authentik-middleware
          namespace: authentik
      services:
        - name: pgadmin-pgadmin4
          port: 80
  tls: {}
