apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config
  namespace: home-automation
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-pv
  resources:
    requests:
      storage: 1Gi
