auth:
  existingSecret: redis-admin-secret
  existingSecretPasswordKey: redis-password
architecture: standalone
master:
  persistence:
    enabled: true
    # storageClass provided by global.storageClass in globals.yaml
    size: 2Gi
  podSecurityContext:
    fsGroup: 1001
    enabled: true
  containerSecurityContext:
    runAsUser: 1001
    enabled: true
volumePermissions:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
