# Default values - overridden by app.yaml
name: ""
namespace: ""

global:
  domains:
    public: "starktastic.net"
    internal: "internal.starktastic.net"
    media: "benplus.vip"
  defaultTlsSecret: "starktastic-net-tls"

ingress:
  enabled: false
  host: ""
  domainType: "internal"  # public | internal | media
  port: 80
  serviceName: ""
  auth: false
  rateLimit: false
