apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: benplus-app-cert
  namespace: traefik-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: benplus-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.benplus.app"
  dnsNames:
    - "benplus.app"
    - "*.benplus.app"
