apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit-strong
  namespace: traefik-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  rateLimit:
    # Allowed requests per second on average
    average: 100
    # Maximum number of requests in a single burst
    burst: 250
    # Measurement window
    period: 1s
