apiVersion: v1
kind: Service
metadata:
  name: traefik-internal
  namespace: traefik-system
  annotations:
    kube-vip.io/loadbalancerIPs: "10.9.9.90"
spec:
  type: LoadBalancer
  loadBalancerIP: "10.9.9.90"
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  ports:
    - name: web-internal
      protocol: TCP
      port: 80
      targetPort: 8001
    - name: websecure-internal
      protocol: TCP
      port: 443
      targetPort: 8444
