---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-secret
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    email: AgAP1T1Ixb9wYxy5Ftdfm4dpoUJ/5ij2npoaZZfpbQwzi1Lfb0jdfpr/juDJP4Eey9x6nfcibNaOIkjDkRJXf3BCduVE6okqtWGku5FtMElYZgXf/DiGxUrronKif6JgNN5ijlCjqXN2vxuCAaPYFD+A8q2DTVwIo4F9Z9uVft8fPGd/rZG0ynz9l64jXrE73+P5IRbjIoJFYaMBuI9BRZ/AUoK7WO31dSHm91uczmAE5sJDzgJf9UZFhdyd35ILDNFFvNv1zp2wsC9fM3mFFW3n0/Uzkfi7Ek6sinOCHRkidbKq6/i693JGvbGbGPB19JqTLXtkpl/Ijo1xFp75o8MiecX5ePWbaa9KT1oOQEg+UKV+6fYUiasvfEUfV8NKI7oW8bknICNWQAaSkVEk9bX5QQXrLOwnpmv7MhiKdibEsMK8axif5PCW4pU9trgIJ86q7yLOzG3dn5lAvAV0b8Hyt2ZIMgcTagPvo8IaMQwx8Q1sVuV3Lr4v2iW2ce79N+sgZ4dRG9uB7Rw3YORo5nvj6UdLgYNX0um/+eqvpmpJxyV5PR3jfkbEG3lvJruFlv0OLfT5j+wPvqn6E5jDmATZKvKwNf9seavjlFbXp6b237pow22f+Ckr3L1fIwIkvO6+UGXcQ2tlCzCmi/6G/DkO2pucT4ZCd2EAgQYEWrcrZGUNXN/c0vxD3uWXhOrneIYwge+x5z6LXEqGNHPmdfj3HsmC62k=
    password: AgCOBYRevT3RNSNqldqmbP1K4qjKW29CQG3EMkt425PHrsHzMUZwmRs09WrWfByeLor224G7xEdGdS4XtGL5CKYhqVdSKoejFUz4iA0AyLccpu4s4UeT7tP2gIVcXldqG/9voFiHayifps2ol7f/NEqcU3gbXU3GPFPddN5pi5ByvqRpahS1w84MGeBKfylQwCNfG7NBk3M4kkUTD4Lt9IJBsNhMqp8Bca0lBdVEcsJMILcEmXE2EuP28F5huGPiPKRfMoDSerKYNQh9DSnqKH23g1UFRL3jj584ER3efrzHgA4Qm4UC1n0lwgGLVYhA4v8r731yeYp9brjzgjdrHyY+LA1TlkWtkDdi/oVu7gDk+aALyNpxFPr9/7k7MGhf37MQlsHs5F5R/jizyWZmawro8rbXZcsT9T2ge+eshZd8xoIGM2comaioRkaYK1XlY191mepVLerXuMXO7O12ty0VqW0qheULgFiGuuXKDzH11TGEhIMYNkmmIBW17wdOnYuTKOJK2A1Ah7bQ81NYoOWWfsXGvVIWHdZmVwHC88Mtn/w+mHavg3xhcTdJ+qX5vyp11OOiBbn4i6bKyJ07i3Unb5qzULk1kHWCqVGcwV4GgohrarB9dfSRY4QgNM7UFtdq28cC52+b8gASroXrH5SVfxzN1TIWFELeadB6/ZtAoZqxG+sguZ335qCnGNmtbHXFQS9KaKdt07ddcMwDdpeI6cAqCQ==
  template:
    metadata:
      name: pgadmin-secret
      namespace: databases
