controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: 6.0.4
          digest: sha256:6d3e68474ea146f995af98d3fb2cb1a14e2e4457ddaf035aa5426889e2f9249c
        probes:
          liveness:
            path: /ping
            port: 7878
          readiness:
            path: /ping
            port: 7878
          startup:
            path: /ping
            port: 7878

service:
  main:
    ports:
      http:
        port: 7878

persistence:
  media:
    enabled: true
