apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-pv
  resources:
    requests:
      storage: 2Gi
