nfs:
  server: 10.9.8.30 # source: globals.yaml → global.network.nfs.server
  path: /mnt/apps/pv
storageClass:
  name: nfs-pv # source: globals.yaml → global.storageClass
  defaultClass: true
  reclaimPolicy: Retain
  archiveOnDelete: false
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
