apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home-automation
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-pv
  resources:
    requests:
      storage: 5Gi
