---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-ldap-sync-secret
  namespace: media
spec:
  encryptedData:
    jellyfin-api-key: AgBgxkGFZHN4mByi4bM07PxVs3rBTROFvMJ50BSpXW5iGXWo5HyAZ2HmBkp/wweuxSoGjZLbJiQkNAWekEQUdw8//PTGpacBPIXJEq5d49XgDIswUmeSOSGJ35ZpVrT3nyZT7m0tWW1qvDFVJxQqRPqK2jfWmaHZ0jbqmNXcFRUc5OKrzG0pRwPMhrRWOxdfnXjCGNt0fE/XPk/wg06q0uulB3pRlX81IwhslXd5laUVYhvEJCvEu8hWynosqBZeR1LHv17fqwqmuJ9j0N/nfmoBy/5TrkfMfBumtdz5bBCgXqCBUKJ9BB1rJzM5SDye1lqQdcJ/8ZuPYMh77E6a+15DNd0bgJg1kSkobjGoxdstYcHS2a7QjD8ugQeCgifBMj7ZWVoYyIbPnADEMKrlt0mp5KEfAwzJhCZ2Nb2PCDE4sc6gK5cQzfEouwWHY8IRLHnbxJkhmxFabgOq1fe8BeMzDRraubr35f6oxZ6xfFCKRwJWMXkL8qqHrzyrcSvS3A4Wsw3gu/bX3sKGW9SKTfbCuxeLHCcrjSZoAXCKXeONrUc8Zm8DAiHI2ChawA9sTWTlPbW42M+a9oxUNroXDnlEl1hPoBZf88qEt0beiPPCXNOq1n0aVmrRzJdEcDO8U+pI22eWKsi6GbXgp5J1Ky9V194/xGYHP3TWBXHtQrMUm0O8y0ohWWx2OoZVUnYjUH9NslfbyAW+MpQnmWaLyMdPkJgIJgG0X6LH+2mrLDMxLA==
    ldap-bind-password: AgAmjNNzcKu1BGF1mt77+TyMOXdTl6sgktPHtvQSCdYDq0B2rAac14PuoqCKlikeN790cFqrf5bnL4NRPuuGeJdvX3MfuXQ++yaWFU5NAvj4PAgtzIngQelnjUk0Faj7dweUC3bveDuWpOpmq7e90ftAl0sib7r+3WnIuoRpn5tT78Vyq8av4ieLogeQ3smWQnnNTVxVXQLMIt5B6Gx0hSH4S/KgXrw7uPiGa1q/q4fZwdzc1M9o5BUv8gSbPlCGMLGlHdsMwxJd2GoKlNawMCJVo4Si6WfI6EIyVqMVGkK5O0ZZa+NkUkHUv7N+mjfvjdi+9IhxOv38MU7RQa6jjf3fadMb1dCYlDbsebrp3FPHpgvkEtPg1Xsv6p2DMuvDoVFqL7YWAITzxB16Cd9X95Fo3wr2cq1jk3inpe/VHFyFyqM85OT9x0FqO1qpolUUfTyV0/Yy3/f0NP3I4qeHfcfYtkXWxYK4ZvWoJVSB41rjo1KSFRvZFWbowHCwEFb2arStmMW7jy1WSD/Hyi7C1E0We6lEMeah0zyg/ijHqzdH+vU6cI6CtKil7JjmESIe5HcGAroTNhBDlSzBM6ehnWaKaeyxVNw2fqo2fzmSIRHOvCypnRKWo00hLaK8elBwwvyuIrO0MFWg6dPpIdAjxLDSuS99VAMTgEhLvv8QcVOCW09Jq88ui4S+CapuwSpy8Yx7MYcWTMgdwoO4goiRRKqY
  template:
    metadata:
      name: jellyfin-ldap-sync-secret
      namespace: media
