---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: maxmind-license
  namespace: monitoring
spec:
  encryptedData:
    GEOIPUPDATE_ACCOUNT_ID: AgBU6fQnGFVfskGw7bIKUISS6K10kDqeMkq0nO+ic8Fv1yhsUWDbDHl/ckTkEm+ooFFTKL66Fb2axYU45fcx+HaP/31BiZ4pK+fRR2VSthotKYl6AJgPkPNS+E6qUbnU9wsgtc8j7rjxFuQpPDdXi2XzjgZMas0loBpaas58jcjbSKTkiMQzPO6c9eJp0JHakfUQOyNl5Vtwb8F55DWpYZxOD1qkPgquuwiSr1Rf4ar+5u4vlSRB1ocP2daPBgk+m1sh/ozYgyWDR8bbuGf/kvHnQ34MXLwG6BBRa8HZ0h1tI3nuDisKRjfugbrWV7Bq2sxBa+D2T4Lrk+T0oXezMgL7Cbp6T4a4dTb966g7Go84GByrav651g5b2yK88Jd3avhEE9Hw2lKVoX/ud424sjqO1jKGymnc+Ct9p1KQx9DV3wg7pz5VYqxfT6zmAH3URzXSy9aci+w+GkYodSNSlcEgbPcvt6JjS+ZRMBNeXTS9TwtkWejdRrLk2YAMXG8fxjiLXsX8LZ/+fGNW6ggXUhLqcNhueujfPNuZi7MJim6YlpTtHnrsk29znrYpRBbTHTnSYSos+6YuemW7cPsDSwp5I2rt33nPl6zbI2kxXqgtFt63Rv5uFydLgk/o7FHkUhrRAHulB6MT9fV9fTOyk7NMmbP8sbw8Qa/+o9oJeBvE/7m3ozjaL654/O0wb83BDWe2Bbt+hCe0
    GEOIPUPDATE_LICENSE_KEY: AgCPsrANgsB7yMGypRiTxxW1dXGVsVH6D6XOcEL5mXcZXrRjB7dKyjd9vd0k4kxUyMbEMYgaj8Nw83dss4rlGcDTcuMWd/iqJ5Zrel8GjTcoonBxDtWWP0bYOt2L8I1mYr/saebv+BqF7E36sl9bEqTk93QCw5Sco1kNi83WUTYXEh1ckhTdAt9zWm0yHLYVBaxw5pAF5+Dy0vWZomJEYZeWlwM8LzKOzycb2hSxMW3B02fW5xUI6uY3RWmijsIWpyR8GlZ0004/idyYr1V2NaeS8XmFr2aLhWHD9QS/qPNXMIEvX1yF/5uAgXLLED0vJLS4Mmhjs6cEb0NLFEgUpM2vaxFizAG1xP+VbINNZkILtW3yPqr6AH0fw0n9nscv1ZdxopfVjLvY/RzHSk9f3RJSCEMkTEqNFAuoBmo9hiLL7z6li4nbH04kNtU2/rSG8DttVhi+i1+fbG0PzpmqNGHxptQ6ZSZcCt5w7zEG8KGZx1SDZKGITvSUILmL1VM9R5Dht0SDlBy20qCckyt5RVdF4W4nrz8Ok5RNwzzj8BPFn0uUCUOwRBYGfHHqNEk+CRe6vsW9wHHVUWhZwEqBXnF4x9ZP7JcPnBvZ+RQNee5dk/9H9TCeJoT1NIq+tiOMVFWLHZM3px6dDA5ST175sWbiE2g3vu+A35OlZbNEjiSuMke7iyHnA1Mws77f1rwe88Kb2bKeNfWI5TEuNpqQrs+N0yzPQzqkt1qIcAbcOsf5t/fOCOWWlV3H
  template:
    metadata:
      name: maxmind-license
      namespace: monitoring
