---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellystat-secret
  namespace: media
spec:
  encryptedData:
    JWT_SECRET: AgBr1xnEkmCTKCe7/OuZFbA7GLAv2ognROZNJ1mEo7t42ro4tmleTfF4UCBWB2y4fwKBleDBWg6sJhS66RnSRm/r2Swx2qwCN5tdUVuGI8YJd9P5WsHjEVWeudRAEM9Bt+1QaMHcj4/ax/SgwajqJsEpwz6CwIevkCNGRH+m2r9FerReIDnPR3QhJBcbjAziAEgwaYFYtAUFmUm4i4PEbGVlMsluZnqJoy0QWMnieobw0P4xM+5YspISOnSYeVV0IEr6IoDDQv8+BsIQvcn8x7tLc+qJUKPzhQN7QXwm62wUgiwd8xQHMaz1Q85rli4PiUZq/B4HhHt0y8NSj5O5NW5gEnPX2pMHIt74recjcq8P3gXVtP6oCXdBtWJndtg6Z4YtT1WbwGyghq/GFy/7Pn4itUE1z9yckuX69hC7sX1J5/1Z8akLePJaX6w8FHQK3tGgonZ0Ca0TUtoxdIe+x8z2WlMXMBXyJ/qaQG/UFHL9HV/ErvTMfiLkeJErbLCDYbUtEnHflngUgxxiDK/+Zp8HNljkss8vpyd42qdhKtbZR65U+6M1OSC+JUjxxSyI2wQTZXY/NAsjxlcWy2nkfIRvIjpRGGSfFYHY6q+gEzWSlPksgWB9U5bGgxYihl4oBzrHn8GEe23UDsPSZGVOeaPTicI5m1Jb+PInXCco2e0Cco8IED4wLPojW9GM+YiZhA2GfzI26qA3WqGiiCIRdIGhlLqk6ddh2atrVenQNs8AImYof+HZjv7TW7zCU7qm82blB0VHqAo2OdV3n5SPizhV
    POSTGRES_PASSWORD: AgCb1nxyjqtMntTR88F4VfWYqt5TczMIPU4uS4GECi+eYYiu5GbAfj1QZPdwTHu821oVY+vsvTkgNxT/fTOzNTeB3zzby8zv6tbuBs4zJI34zMmUW/6wUD7UYgxDoe42DiBSpHLrXSLvjGC3gN7dF/ytViNqMRUEW71PHAdRMtKCNeQBrY80ihZn0CZk7XsqfQ4va/wZ9hEPXEXJW0F1TV5fqQD8bpypvYSHtb8gEjIUdgNIkHaCd3MESOIzEMj1vfHqHNTu1D8lmABqqUeqeRXkVWKCV+4XMfbrUEJTfq1zEGG2DvfAdc1HM5gmqc/vht5GjObcPS9916TlU34odabz40/A4ORbLLEe/avldToWIZy+zp+DLR+JZsZA21N9aSE5Q9HvVPDrQGbuI/p3vE9+LQp38myojW714J46nIiN4wi6y/TtroaOpdJTcCyf1ExD5yZ5dRgfHqAIglg/yKlnT/0EU6CW/S3EzU1suGHLOpjP/Q5QAQPcJ4INgXwJEiJhZgdWjOmMf27CTl4o0GrhGM09qMhe5v5ao2eNgmESjq+GOXorlHetPekD+FMJRwRRV7IooTwgdPw2Oz4yd01namAHoh7McAAF0hcPpbK1fv30ueo7iDaWniceffkm0QYr8TndaBgos6NnirowfTpkycNUgGwiFNrw7b1I+TGTXOQMavwBCsWTymJeraNVZVpdnRfpKakDW9FDAQ0=
  template:
    metadata:
      name: jellystat-secret
      namespace: media
