---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cross-seed-config
  namespace: media
spec:
  encryptedData:
    config.js: AgCbEFfz1NBYAlzKxjFeoYVm7PSoIJJ6udCmdyfVlbvG9w1AtNgGrYFG/TtCWD/ipu1y1vIgc1CjS05MzDshBBKvhFzJfSsyP1TlCX9J+Bpuv2/kEH/mBvbk9lImzFFqGrDW5/x8YkhiDTunBmriTWy8riFs/6Dz8II1Ax/KZRxz5i32Tsdv/nBvUTE0uNLQ7tT/gfFD0BmftaUmmN/4nslvko47Oei5NwHEOLnblOnhXdpJYXlPdZUS9V7cPkQ/jFeHiC+Mh47lwSnL7aQAx5tUtwg1znOVLqGcGAksQcbX6gy0T0MaMyUU0xjF2CO9Znb/VZvHvOn0Cco5pmlcwjdewOr8l/zLfZJJESuH+spPg6uNLPyPriv0BPstLn6l3pqZNBy3OCj8HKOVIPSmzywpLYirtzEqYgxsRjJuJ6CxNsbdntoVCUq7Wtj6qmiOh+oJrQ4cpL3gB7QR8eipZLw6FGFHW/TW8oOr8OIslFHoo1uQJCo2nvZPr4aTBweIfbwg2IO69O8wXDVldH3NOgGS9e7p0++pehqmVfIV31KTUG4e+rRhOhqbsvmIYhAJ6HmeKNluTGXYB5RO0W6z+xICXBwjvZAaR3160sNQJosb3ZzReBjn944wwrugI6GELAdhPW8g+8tOjEydcSy7uuIEUAcbbK0SdDHLAg9TDi1gq6qc80m6jeqkkvaNQocppqDiOKfS1xBifpfHOanA2Xhp/pgA4CcjQERvkTz8Pl4qycunBwwLcxziSM53dgPymq6ATanojnajxgdcDGZTdVv5eF8xEW+fK/YDQcfR5R+Gan/iNkAFiipR472xXxkavAxvkOp78HIQfCiREdNWvcmu5tlJ7QqQSQsYp4eWeedwNI8ErVk54FI3yKqDCqLstp/s/dQx2PDqmtWGvSc/hlVQ161D+7Hf5MCcFGOVW5F2pRl79OVOCBUCPdRTtzXuRDDwsjdSKVDdpcy+vSxI3ca5uQBMYXTqCq6LD3JK8i3T4fj9Q6E2gdPMWLLSsjzn/+UeRJnYvAwObne3h8rjVkUq9p9TcVs/HF30+2PGwAMj5V3JwjA7+si2kuMIOu7kiCaR02+VFjUkO9n4j24FOa2q6KohR08E5Y05xJQnS6y+awoNw7s0a5GqtPLpTxIVfAKBxVw25vnYshylKS2FFouRtfh/Njw3iYc9HDsa2C1phjDTx1LodH0exkFHiPFDUcFAMHvjnMGfggMcju0T23+UP1Twba4isNzA9gsNfW4N1sZw0+2GPlSmLQbYE9AL2tljgCUYQtuTVZ3pcNCvrxbYcwhLzK/WOpt4y23c/Sg3eczCxrG+pbZS4d54tjkVnnlrdXBFzpI9+R+Z7ld9mz3CW9+pCqIq0ypIlG8aTYDZkW9Kmv8=
  template:
    metadata:
      name: cross-seed-config
      namespace: media
