apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-admin-to-internal
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  redirectRegex:
    regex: "^https?://auth.starktastic.net/if/admin(.*)"
    replacement: "https://auth.internal.starktastic.net/if/admin${1}"
    permanent: false
