---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-authentik-secret
  namespace: authentik
spec:
  encryptedData:
    password: AgC45mgLA1MP4t4QJXRbQ0Y1DRgfMx9/7dQse+q1v8+1uetS7z8FjhkGYPlPF+wYNqBX+f9OvoF6RzKs9xuiHC2JtIf03setvbQXmsDJh4v/1U/SOmWYJ7V94q8ON+cNoLSeYBcIf4waGKk35CvwiZ7S2FE7r1EhpQG2ejqJx4ojLIJ1VBdGI/pi1yAFHjZHGDJTVGKmplw7UPJ/2LT5QrtmYzGuU0+lXn+PiSPbjNu3H5HK6PuvfXYN051ZA8RSe7Ldok2xHjJynuR+qDH6rwrKYad9iVNnC3XJZsxPAlXO0enSBHanq09ta7tikYdMur1Gjocz8IULCq3+HIW1xlih4OA6XS7MZjg81R+erGsnSNfJASk+NUKncl7TaH9YdmWmaTjQeiQbD2UqYzJhmhUrQ33h5gca08fSpdfVI7hWyFLJnrW4YeGDn9axqguZ/iguLZvkw8+TpMH8bbfv3zXvKgpzNGmCp6kHaFf9oLH5TaHPjSxaO/aH3CrCNfrWnTTB2l+227LzXYZUYQHlAttrXmJFzKAEkZjiCMddhtUQnw4yh96brf4BIFJv7ktrGaCfcZn57jnnsIjF3tT+pCoKzN4OJBdfgGX1/mDYDyhGtNGxEYKpi5GW+mSPjPrktpC8PyXK0NMuE35IR43RT8aHhhe5xXnpoyKaRGhReAwZiEbuufdZdS0EYMjYkt67YbnZDjdtf3oeEk73FtUmK4B1Tjmm7URGtS/jwpUaBEDXZdcNU9dL8KWwhudgLRSzMNTGSw==
  template:
    metadata:
      name: smtp-authentik-secret
      namespace: authentik
