apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-root
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`benplus.vip`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
      middlewares:
        - name: rate-limit-strong
          namespace: traefik-system
  tls:
    secretName: benplus-vip-tls
