apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starktastic-net-cert
  namespace: traefik-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: {{ .Values.global.defaultTlsSecret }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.{{ .Values.global.domains.public }}"
  dnsNames:
    - {{ .Values.global.domains.public | quote }}
    - "*.{{ .Values.global.domains.public }}"
    - "*.{{ .Values.global.domains.internal }}"
