controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/prowlarr
          tag: 2.3.0
          digest: sha256:e74a1e093dcc223d671d4b7061e2b4946f1989a4d3059654ff4e623b731c9134
        probes:
          liveness:
            path: /ping
            port: 9696
          readiness:
            path: /ping
            port: 9696
          startup:
            path: /ping
            port: 9696

service:
  main:
    ports:
      http:
        port: 9696
