apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  entryPoints:
    - websec-int
  routes:
    - match: Host(`argocd.{{ .Values.global.domains.internal }}`)
      kind: Rule
      middlewares:
        - name: rate-limit-strong
          namespace: traefik-system
      services:
        - name: argocd-server
          port: 443
          scheme: https
          serversTransport: argocd-transport
  tls:
    secretName: traefik-system/{{ .Values.global.defaultTlsSecret }}
