apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-pvc
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-library-pv
  resources:
    requests:
      storage: 10Ti
