apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-config
  namespace: home-automation
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-pv
  resources:
    requests:
      storage: 2Gi
