controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: 4.0.16
          digest: sha256:37be832b78548e3f55f69c45b50e3b14d18df1b6def2a4994258217e67efb1a1
        probes:
          liveness:
            path: /ping
            port: 8989
          readiness:
            path: /ping
            port: 8989
          startup:
            path: /ping
            port: 8989

service:
  main:
    ports:
      http:
        port: 8989

persistence:
  media:
    enabled: true
