---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-secrets
  namespace: crowdsec
spec:
  encryptedData:
    bouncer-key: AgA7wXzoF5aeef11YmDwhbTNWmJ5khmo/IX6Kq8ZvCpobj1K0MGfsEzNFIYfm9CtEcA2HtLGOXTw50nTRTqDb+p9mYASH1M4tOWTjh75FGfffbIWpGTZphRVWMm35ELl0jyQsAj+KhCKrcBmI54dATyCNsbRXQId6kJysV7QhrLs0B6mvK//1LgQUNcvJf5cV3MDgcwWaD9iHU04+MP5FlH4kMcoO3cSbK9WiSHcZvd9GWsF32THSLTC59rmk/BlYXLglSPNGtZ4oL/WL+p7PQVUGwoBtH6LgfCSExS1fTAqAo4nx+ghVLQxfNWVtG4er5jpet/WqZfWBknpwaRxf72HRGJIs171xu3FQ/fksAsTAVNaAVUBCO0n/hhLihfRATfwlMDvCA8/bMpw0c1PMarN4Hy8W+y7ZnzhVIVstOMSXM2dyN6za1E1/47l/UL/GnbKb7tR4sr5eGwQvghH9Rl09h0fdt1rKHos1HhisWbvaWw+G1MuFbhWxs57Xg6eVg8D5OXH3WlpbVZhLPqp7CPGkSnPaUX5wsn36rv/wHNaAP+ulNuw/rVvfLMkuJ1WhxlCCBe4fG686RhD8QW8g0uKa41QyY+s7dZ6ABc4J+zcAYhuAaQ76CaZPg8M9c0mxGZyV5clk/gbstcbfydj5irHkvwtHdkA/GcFMqumVhx3ocUM5TDYhjbnjyQyDMitEkcXxjCePm/5j997HRLGGYW7519ATbkHxgKq/Y63GC7A0ghQ3avw3dy+TMuHPjghrM29IL9BFLbQTw4AW17HM0O3
    enroll-key: AgCNRh5rybnZjL9A+sYb4QhJJbECW45AMBOhAwgr1qgbczyIownjiPEPtcOxrtCwWbyJKxvWo1GkBVSJofoCOrVdSt3HTzsEXZelqP26HN5ieFuo3bRsB44H4/A9LElGOGFPowDwVtssn/uKID2aPJPRcYNFoyi62R7hW85qYnQdNxx7kfB7sLZt0DEi6GkGHVCCx7Fq24a+cFVAu/AM+hj8Gfm2nf7isgQU3IvdixJzGz6QGQBsPHOVR7/QFNRkn+Oc8gFM2qkHL+2FT5sLkwm29CnXELmZrBGwQ7RHVEutfjdM4/Mnq4WpCrS/kC59qwOb+NA8jeO9V0n7eLoemfVYbleR4lquIB6nQdIY4Sx//MP8ViR8KuJnHTimo5FRvuypYYZcGWHgC2+1TAwsdr7UsyH4yoz71FYR0cR/Hfpq+YnEhXhpq8kR3D867qMJzKXMVsH7hQ+gxNU5tD5h3H/VzFOyR3agFclfbi+pYptrdKojb4Ge2EKnC4TIqgMvJrz1uE6EGFiQfWCM/LtTqEBHY1OG0HMFJemm5anrZZBIy0grK7yBZvdJZkcllnU0IxbUjGk0aWqW6iiQCpVEW9tcArG9DO/rsGd7rYFmqvghCu0cc5yQMGg0wwx+jH0VFFgGnmpMvXWCWnmXBEtWftDbLKIqNK6+fW5AagsUzYFcEm/0n0iyyCkBMRz6HfVygFyYX8UZrn1qXv7k6tOROuVxRmAjtEdA6LCr
  template:
    metadata:
      name: crowdsec-secrets
      namespace: crowdsec
