name: kube-prometheus-stack
namespace: monitoring
deployPhase: services
chart:
  repo: https://prometheus-community.github.io/helm-charts
  name: kube-prometheus-stack
  version: 82.2.1

ingress:
  enabled: true
  host: grafana
  domainType: "internal"
  port: 80
  serviceName: "kube-prometheus-stack-grafana"
  auth: true
  rateLimit: false
