---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-authentik-secret
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgB3AUB+qqEkfvr3xnr5QDy4qHwkNAihfaXIvIiPGBLeylBsak59p5r2yN1LiXWP0umGGjlnyJBcZ96mJ6eOheozsdcpv/KcGEltRz9EOiezPrwIg88HZrqVo8zniGp1rEt9GJ0iMThcn6o1mWhLSB5zIc+PpNCYPRVKtSrvx+FG8yGGCHriRBNz1F+cVnfdZlSXyx7VQ352gjcFn4iVZSaCtJaJKohpwEYUSADXh8T636S0H6vTbhYKUlTCx3XTZJjbC5j4UCMNJm4z+QJO6zlMWXLAiFxKBwMqddrA+Jy4YADSC4j/k4nq5XyHozXgQcIUKTndnb+xce98+OSl9kPVzPTNifadjHfMAMBsi6Ug13DPMkfzSIyw4ZFocwcN2WiG2HDcPO9T46J3o6RN6e3Fab2lyuF0vjU2E4xrUBqN0cutOShPl5PhT5DHzTNyr/xfbQE7ZK6pCza/P2MvW3LIfAs/zYo/kjNx4tB/3V4vb+DTfNRgYVKoIQSOEJ8YlKMgF9xhyn0hZvsrUIzPy+ekoTcsByOTFGP7vhMKGdlw0grByGB9QAaNtsi1bx/v2lTlzJ8y5gyI5pG0Lj97FdutzzCrVuRrhRp4kC4jt8QS/qnkmCas2wQVBacaXvJ1jI5D6gneaqpqcfchzo44i57PiN1sISkV5irNmQB2GcWendAmGRhHJbFFb3eTA8+946YAgwWkQSyxrFGsBIucWESiSm19moJzNl4wGYmMXJIVVrFMC7+g6m5MZrm4HLz3YDDczA==
  template:
    metadata:
      name: smtp-authentik-secret
      namespace: authentik
